# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import *
from Designer import *
import cv2
import numpy as np
import csv


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 340)
        Form.setMinimumSize(QtCore.QSize(300, 340))
        Form.setMaximumSize(QtCore.QSize(300, 340))
        self.lblImage = QtWidgets.QLabel(Form)
        self.lblImage.setGeometry(QtCore.QRect(20, 20, 271, 161))
        self.lblImage.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lblImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblImage.setText("")
        self.lblImage.setObjectName("lblImage")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 270, 281, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnUpload = QtWidgets.QPushButton(self.widget)
        self.btnUpload.setObjectName("btnUpload")
        self.horizontalLayout.addWidget(self.btnUpload)
        self.btnConvert = QtWidgets.QPushButton(self.widget)
        self.btnConvert.setObjectName("btnConvert")
        self.horizontalLayout.addWidget(self.btnConvert)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 200, 281, 61))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lblBinary = QtWidgets.QLabel(self.widget1)
        self.lblBinary.setText("")
        self.lblBinary.setObjectName("lblBinary")
        self.horizontalLayout_2.addWidget(self.lblBinary)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.btnUpload.clicked.connect(self.load_image)
        self.btnConvert.clicked.connect(self.convert_to_binary)

    def load_image(self):
        self.filename, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open Image File", QtCore.QDir.homePath(), "JPEG Files (*.jpg)")
        if self.filename:
            image = QtGui.QPixmap(self.filename)
            self.lblImage.setPixmap(image.scaled(self.lblImage.size(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation))
      
    def convert_to_binary(self):
        if self.filename:
            img = cv2.imread(self.filename)
            grayscale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            ret,threshold = cv2.threshold(grayscale, 125, 255, cv2.THRESH_BINARY_INV)
            threshold = threshold / 255
            cv2.imshow("ss", threshold)
            
            x = np.ravel(threshold)
            with open('binary_values.txt', 'w') as f:
                x = np.ravel(threshold)
                x_str = [str(val) for val in x]
                f.write('\n'.join(x_str))
                
            path_excel = "binary_values.csv" 
            np.savetxt(path_excel, x, fmt='%i')

            cv2.imshow("ss", threshold)
            self.lblBinary.setText(str(x))
            
            
            #--------------------------------------------------------

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnUpload.setText(_translate("Form", "Upload"))
        self.btnConvert.setText(_translate("Form", "Convert"))
        self.label.setText(_translate("Form", "Binary : "))


if __name__ == '__main__':
    Uygulama=QtWidgets.QApplication(sys.argv)
    penAna=QMainWindow()
    ui=Ui_Form()
    ui.setupUi(penAna)
    penAna.show()
    Uygulama.exec()